import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { DomainConfig } from "../config/types.js";

const CONFIG_FILE = "testlens.config.js";
const PROMPT_FILE = "TESTLENS_INIT.md";

// Roots scanned for product feature directories, in order of how strongly they
// signal "this is a feature". The first root that yields any candidates wins —
// we don't merge across roots because that produces noisy taxonomies.
const SCAN_ROOTS = [
  "src/app",
  "src/features",
  "src/modules",
  "src/domains",
  "src/pages",
  "app",
  "features",
  "modules",
  "pages",
  "src",
];

// Names that almost never represent a product domain. Filtered out of proposals.
const DENYLIST = new Set([
  "components",
  "component",
  "lib",
  "libs",
  "utils",
  "util",
  "helpers",
  "hooks",
  "types",
  "constants",
  "config",
  "configs",
  "styles",
  "css",
  "assets",
  "public",
  "static",
  "common",
  "shared",
  "core",
  "node_modules",
  "test",
  "tests",
  "__tests__",
  "__mocks__",
  "mocks",
  "fixtures",
  "stories",
  "e2e",
  "scripts",
  "build",
  "dist",
  "out",
  "api",
  "middleware",
  "layout",
  "layouts",
  "globals",
  "vendor",
  "tmp",
  "temp",
]);

const PALETTE = [
  "#f7a44f",
  "#4f86f7",
  "#6abf69",
  "#ef7f7f",
  "#a47ff7",
  "#f7d24f",
  "#4fcfd2",
  "#d24f9e",
  "#9ed24f",
  "#7f8aef",
];

export interface InitResult {
  configPath: string;
  promptPath: string;
  domains: DomainConfig[];
  configWritten: boolean;
  scannedRoots: string[];
}

function isDenylisted(name: string): boolean {
  if (name.startsWith(".") || name.startsWith("_")) return true;
  return DENYLIST.has(name.toLowerCase());
}

export function toDomainId(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/[_\s]+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

export function toDomainLabel(name: string): string {
  return name
    .replace(/[-_]/g, " ")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/\s+/)
    .filter(Boolean)
    .map((w) => (w[0] ?? "").toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}

function listSubdirs(absDir: string): string[] {
  try {
    return readdirSync(absDir, { withFileTypes: true })
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort();
  } catch {
    return [];
  }
}

export interface ProposalResult {
  domains: DomainConfig[];
  scannedRoots: string[];
  rawCandidates: Map<string, string[]>;
}

export function proposeDomainsFromFilesystem(cwd: string): ProposalResult {
  const seenIds = new Set<string>();
  const domains: DomainConfig[] = [];
  const scannedRoots: string[] = [];
  const rawCandidates = new Map<string, string[]>();

  for (const root of SCAN_ROOTS) {
    const abs = join(cwd, root);
    if (!existsSync(abs)) continue;
    const subs = listSubdirs(abs);
    if (subs.length === 0) continue;
    scannedRoots.push(root);
    rawCandidates.set(root, subs);

    for (const name of subs) {
      if (isDenylisted(name)) continue;
      const id = toDomainId(name);
      if (!id) continue;
      if (!/^[a-z0-9-]+$/.test(id)) continue;
      if (seenIds.has(id)) continue;
      seenIds.add(id);
      domains.push({
        id,
        label: toDomainLabel(name),
        color: PALETTE[domains.length % PALETTE.length] ?? "#888888",
      });
    }

    // First productive root wins — avoid merging competing roots.
    if (domains.length > 0) break;
  }

  return { domains, scannedRoots, rawCandidates };
}

export function renderConfigFile(domains: DomainConfig[]): string {
  const lines: string[] = [];
  lines.push("// testlens.config.js — generated by `testlens --init`");
  lines.push("// Domains were proposed from your directory structure.");
  lines.push("// Review them, then run `testlens --skill` to start tagging tests.");
  lines.push("// For a smarter taxonomy, paste TESTLENS_INIT.md into your LLM and");
  lines.push("// replace the `domains` array below with its output.");
  lines.push("");
  lines.push("/** @type {import('testlens').TestLensConfig} */");
  lines.push("export default {");
  lines.push("  domains: [");
  for (const d of domains) {
    lines.push(
      `    { id: ${JSON.stringify(d.id)}, label: ${JSON.stringify(d.label)}, color: ${JSON.stringify(d.color)} },`,
    );
  }
  lines.push("  ],");
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

export function renderInitPrompt(
  rawCandidates: Map<string, string[]>,
  proposed: DomainConfig[],
): string {
  const lines: string[] = [];
  lines.push("# TestLens Domain Bootstrap");
  lines.push("");
  lines.push("Use this prompt with any LLM to propose a refined TestLens taxonomy.");
  lines.push("");

  lines.push("## Context");
  lines.push("");
  lines.push(
    "TestLens groups tests by **product domain** — coarse, user-visible features, not technical layers.",
  );
  lines.push(
    "A good taxonomy has 4–10 domains. Each one answers: *what user-facing capability does this protect?*",
  );
  lines.push(
    "Avoid layer names (`components`, `hooks`, `utils`) and infrastructure terms (`api`, `middleware`).",
  );
  lines.push("");

  lines.push("## Directory snapshot");
  lines.push("");
  if (rawCandidates.size === 0) {
    lines.push(
      "_No conventional feature directories were detected. Provide your own context to the LLM._",
    );
  } else {
    for (const [root, subs] of rawCandidates) {
      lines.push(`**${root}/**`);
      lines.push("");
      for (const s of subs) lines.push(`- ${s}`);
      lines.push("");
    }
  }

  lines.push("## Heuristic proposal (current)");
  lines.push("");
  if (proposed.length === 0) {
    lines.push("_None — heuristic could not infer domains._");
  } else {
    for (const d of proposed) lines.push(`- \`${d.id}\` — ${d.label}`);
  }
  lines.push("");

  lines.push("## Instructions");
  lines.push("");
  lines.push(
    "1. Critique the heuristic proposal: what feels right, what's missing, what's a technical layer disguised as a domain?",
  );
  lines.push("2. Propose a refined taxonomy of 4–10 product domains.");
  lines.push("3. For each domain provide:");
  lines.push("   - `id` — kebab-case, must match `/^[a-z0-9-]+$/`");
  lines.push("   - `label` — short human title");
  lines.push("   - `color` — six-digit hex code (`#rrggbb`)");
  lines.push(
    "4. Output **only** a JS array literal in this exact shape, ready to drop into `testlens.config.js`:",
  );
  lines.push("");
  lines.push("```js");
  lines.push("[");
  lines.push('  { id: "checkout", label: "Checkout", color: "#f7a44f" },');
  lines.push("  // ...");
  lines.push("]");
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}

export function runInit(cwd: string): InitResult {
  const configPath = join(cwd, CONFIG_FILE);
  const promptPath = join(cwd, PROMPT_FILE);

  const { domains, scannedRoots, rawCandidates } = proposeDomainsFromFilesystem(cwd);

  writeFileSync(promptPath, renderInitPrompt(rawCandidates, domains));

  let configWritten = false;
  if (existsSync(configPath)) {
    console.log(`${CONFIG_FILE} already exists — leaving untouched.`);
  } else {
    writeFileSync(configPath, renderConfigFile(domains));
    configWritten = true;
    console.log(
      `wrote ${configPath} (${domains.length} proposed domain${domains.length === 1 ? "" : "s"})`,
    );
  }
  console.log(`wrote ${promptPath}`);
  if (scannedRoots.length === 0) {
    console.log("(no conventional feature directories detected — review TESTLENS_INIT.md)");
  }

  return { configPath, promptPath, domains, configWritten, scannedRoots };
}
